### PR TITLE
Enabling Emmet Support

### PR DESCRIPTION
**Pull request by nesper8**
This PR enables Emmet support for website building
This PR will also only enable emmet for html, css, sass, scss, xml and jsx files

What is emmet?
check out https://emmet.io/

### CODE REVIEW

**Comment by nesper8** [comment]
The last commit changes the Default Emmet leader key from <C-Y> to <Tab> to better imitate VSCode although you still need to do <Tab>, to expand the Emmet abbreviations

**Comment by ubmit** [comment]
What do you think about using the LSP to handle it? I had been using `emmet_ls` and didn't face issues with it: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#emmet_ls

We have only one language server setup by default though, which is the Sumneko and maybe we should keep as it's. So people can add emmet support or any other feature when they need them.

**Comment by nesper8** [comment]
Wait so emmet_ls from Mason also serve the same purpose?
I haven't checked it out though

**Comment by ubmit** [comment]
> Wait so emmet_ls from Mason also serve the same purpose?
> I haven't checked it out though 

I guess it does not sure sorry

**Comment by nesper8** [comment]
just tried out emmet-ls 
feels like it is more easier than mattn's implementation 
so ill close this PR

**Pull request closed without merging**
