### PR TITLE
set language to english in init.lua

### PR DESCRIPTION
**Pull request by kbilsted**
***************************************************************************
**NOTE**
Please verify that the `base repository` above has the intended destination!
Github by default opens Pull Requests against the parent of a forked repository.
If this is your personal fork and you didn't intend to open a PR for contribution
to the original project then adjust the `base repository` accordingly.
**************************************************************************

### CODE REVIEW

**Comment by kbilsted** [comment]
what is the styling problem?

**Comment by feoh** [comment]
Hi.

Thanks for your contribution but this change would break everything for any non English speakers who use kickstart.

I don't think this is appropriate for this project at this time. Closing.

**Comment by kbilsted** [comment]
Its is a funny statement.  To me everything breaks for me when neo insist i want the lang to be the os :-) i nearly departed until i found this setting. It is better than deleting the lang sub folders

**Comment by feoh** [comment]
Glad you found what you needed.

Feel free to modify your PR to add a comment letting people know this setting exists if you feel it's important for all users.

**Pull request closed without merging**
