### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mgua**
added a pointer to my fork where instructions for different operating systems are available

### CODE REVIEW

**Comment by antoineco** [comment]
How about contributing changes upstream instead?

**Comment by feoh** [comment]
I agree. Thank you for your contribution, but i'd be much more inclined to merge it if you would simply put those instructions in line.

**Comment by gregorywaynepower** [comment]
@antoineco @feoh I can get these instructions in an inline change in the REAMDE.md if y'all want?

**Comment by mech-a** [comment]
Thanks for your contribution, I'm not sure we really need this, as much of the details are about getting neovim up and running on some less-used OS's, which is better handled by neovim's own docs than us. For the other dependencies we have, it's also better to just reference their own docs.

**Comment by feoh** [comment]
Hi thanks for your contribution but as others have said I don't think this is a desirable addition. Closing for now.

**Pull request closed without merging**
