### PR TITLE
fix keymap for treesitter incremental selection. 'c' to 'C' for CTRL

### PR DESCRIPTION
**Pull request by rosstimo**
fix keymap for treesitter incremental selection. 'c' to 'C' for CTRL

### CODE REVIEW

**Comment by rosstimo** [comment]
In the incremental selection section the <c-space> for example wasn't working for me. Changing the keymap to <C-space> worked as expected for CTRL + SPACE key sequence. All other keymaps had the capital C for CTRL.

**Comment by tjdevries** [comment]
What operating system? I didn't think it needed to be capitalized.

**Comment by craigmac** [comment]
the capital 'C' is not needed, and it's technically `<C-Space>` (capital 'S') as well, `:h control`, so if it did matter then setting `<C-space>` shouldn't work.

**Comment by rosstimo** [comment]
I apologize for creating useless noise. My configuration must not have been properly loaded when I first noticed the key maps weren't working. I fooled myself when I saved, restarted and everything worked as expected. My bad for not testing to see if I could bring the problem back. Sincerely swepped up in my own enthusiasm.

**Pull request closed without merging**
