### PR TITLE
fix: #26

### PR DESCRIPTION
**Pull request by SyedFasiuddin**

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
duplicated #23

**Comment by SyedFasiuddin** [comment]
Yeah, it is duplicated, but why is it not fixed in the master branch yet?

**Comment by CharlesChiuGit** [comment]
it's an open source project, repo author will only review them when they're available. 
creating duplicated pr won't make things go quicker.

**Comment by CharlesChiuGit** [comment]
please close the issue and pr. thanks.

**Comment by SyedFasiuddin** [comment]
I saw #23 after you mentioned it, after creating the pull request. Sorry.

**Pull request closed without merging**
