### PR TITLE
Iterate over #420

### PR DESCRIPTION
**Pull request by saccarosium**

### CODE REVIEW

**Comment by bryanboateng** [comment]
Why remove the archive installation instructions?

**Comment by saccarosium** [comment]
> Hi. I can appreciate that you're trying to simplify here but I disagree with this change and > feel it represents a negative departure from the current instructions.
>
> If people use Git to clone the repo locally, they can then use git pull to update the repo from upstream as changes happen.
>
> With your method, you've stripped that capability away which I see as a dis-service to new users.
> -- comment by @feoh

see #420 

Basically there's no real advantage in having the archive installation instruction and, at least to me, is not very useful, even for a new users.

**Comment by feoh** [comment]
Hi, thanks for your contribution but we'd need detailed instructions on how to use git clone to clone the repository.

If you're not comfortable with that please go ahead and close this and I'll take a swing at it :)

**Comment by feoh** [comment]
Pardon. Didn't mean to close there :)

**Comment by saccarosium** [comment]
> Hi, thanks for your contribution but we'd need detailed instructions on how to use git clone to clone the repository.
> 
> If you're not comfortable with that please go ahead and close this and I'll take a swing at it :)

There are already in the README, aren't they enough?

~~~markdown
```sh
git clone https://github.com/nvim-lua/kickstart.nvim.git ~/.config/nvim
# OR
gh repo clone nvim-lua/kickstart.nvim
```
~~~

**Pull request merged**
