### PR TITLE
add plugin specs docstring, remove lazy.nvim configuration (empty) table

### PR DESCRIPTION
**Pull request by brxxlstxrs**
Add plugin specs docstring, remove (empty) table for **lazy.nvim** configuration due optionality

### CODE REVIEW

**Comment by brxxlstxrs** [comment]
(https://github.com/nvim-lua/kickstart.nvim/issues/651#issuecomment-1966818293)

**Comment by feoh** [comment]
Sorry to ask this but, would you be willing to run stylua and format your changes so the check passes please?

Thanks a bunch! It's what the community wanted :)

**Comment by brxxlstxrs** [comment]
> Sorry to ask this but, would you be willing to run stylua and format your changes so the check passes please?
> 
> Thanks a bunch! It's what the community wanted :)

if I run it it will change everything that tj did

**Comment by feoh** [comment]
@dam9000 thoughts? This was kinda my concern about this check.

I have no idea how to resolve this and I don't want to erect walls to make contributions harder.

Thanks and sorry to bug you :)

**Comment by brxxlstxrs** [comment]
(I also think nice to add empty line before comment i added)

**Comment by feoh** [comment]
I don't have any feelings either way but we can't merge it with failed checks.

@tjdevries do you have thoughts on this and/or the stylua check in general?

**Comment by brxxlstxrs** [comment]
> @feoh
look, the lines that added to commit cannot cause conflicts with stylua, or maybe i'm wrong?

**Comment by brxxlstxrs** [comment]
I think this all is the reason why TJ did not do what I am now trying to suggest

**Comment by feoh** [comment]
OK so as near as I can tell running Stylua generated exactly *1 character* worth of change :)

If anyone has any issues with this, please speak up in the next few hours. I'll merge this tonight.

**Comment by dam9000** [comment]
looks fine to me.

**Pull request merged**
