### PR TITLE
Fixes #607. Add hints for new neovim users to learn how to learn.

### LINKED ISSUE #607: How to quickfix/how to learn about features
Two part noob question I have:
1. I working in javascript files, and vscode often is able to suggest fixes to bad code. For example, on a function that doesn't exist, I can do command+. to pull up a menu to auto-import the function from another file. How can I do that with kickstart/nvim
2. Second, if I wanted to understand what are capabilities of my current setup vs what I should go out and look for, how can I do that? Basically want to become more self-sufficient answering questions like the one above.

Thanks :)

### PR DESCRIPTION
**Pull request by feoh**
This change adds a section to the README around learning how to learn about Neovim features and keybindings as a new user.

### CODE REVIEW

**Comment by feoh** [comment]
@asnewman Can you give this a look and either approve it or suggest changes please?

**Comment by feoh** [comment]
FWIW I didn't make this in my fork because it has changes I don't want to upstream (I use a different theme and a bunch of plugins not appropriate for kickstart).

**Comment by dam9000** [comment]
Very nicely written.

**Comment by dam9000** [comment]
you can now delete the branch, there should be a button somewhere here below...

**Pull request merged**
