### PR TITLE
add Telescope live_grep on Git root

### PR DESCRIPTION
**Pull request by slara**
Adds a keymap to use Live Search with Grep on the entire current git project.

### CODE REVIEW

**Comment by feoh** [comment]
This looks neat! Thank you for your contribution.

Has it been tested on Windows?

If not and you don't have access to a Windows install I can test it in my fork.

**Comment by slara** [comment]
Hi @feoh , Thanks! I tested it on Linux and Mac. I don't have a Windows install available.

**Comment by dam9000** [comment]
Can we keep the old `<leader>sg` keymap as it was (live grep) and use your newly added new `<leader>sG` for the new functionality (grep git root), this would be less disruptive for existing users.

**Comment by feoh** [comment]
I love this idea!

**Comment by dam9000** [comment]
Hmm, another thing to consider, perhaps this functionality should be made into a plugin that can then be added to kickstart as a single line addition, if we want to keep the "kickstart": small, single file, and easy to learn. Wouldn't that be a better approach?

**Comment by feoh** [comment]
@dam9000 Gonna pump the brakes on that one :) I don't want to get kickstart.nvim into the business of needing to support plugins meant to extend *it* rather than Neovim itself.

I don't personally think this code change is so massive, I think it's a decision of include it or don't. I'm personally leaning towards including it but I'm open to other feedback.

**Comment by feoh** [comment]
I don't really understand how to use the :Git stuff yet, and when I try this here on Windows I get "Buffer not associated with file" so I'd guess that's working as designed?

Man I wish I had the time to delve more deeply into this stuff :)

I'm going to merge and if any ninjas out there understand enough to tell me it's wrong we can work on it from there :)

**Comment by slara** [comment]
Thanks @feoh! This is so cool! 

I think this could happen if you are inside a special buffer like NeoTree or the dashboard. I will try to reproduce it and make a fix.

**Pull request merged**
