### PR TITLE
feat: use VimEnter event instead of VeryLazy

### LINKED ISSUE #655: Intro disappears immediately after starting up neovim
## Describe the bug

I got the fresh kickstart installation I haven't changed anything, When i launch neovim the intro screen disappears immediately
## To Reproduce

1. ...

## Desktop

- OS: Arch linux
- Terminal: Alacritty

## Neovim Version

Latest version
```
```

### PR DESCRIPTION
**Pull request by taliraj**
Fixes #655.

### CODE REVIEW

**Comment by dam9000** [comment]
A note, while the fix is correct, now the following comment is no longer correct:
```
  -- For example, in the following configuration, we use:
  --  event = 'VimEnter'
  --
  -- which loads which-key after all the UI elements are loaded. Events can be
```
Because VimEnter happens before UI.

**Comment by taliraj** [comment]
> Perhaps just change it to `before all the UI elements are loaded`

Good point 948004162ace7dba1df7fcce7b7fab1f3efd29f9

**Review by dam9000 — APPROVED** [review]
LGTM :)

**Comment by feoh** [comment]
Thank you for your contributions everyone!

**Pull request merged**
